### ISSUE TITLE
doesn't build for jelly bean

### ISSUE THREAD

**Issue by papofrito** [bq/aquaris-5#1]
The command for building jelly bean doesn't work because there is no mediatek/config/eastaeon89_wet_jb2 folder

**Comment by pmoncadaisla** [comment]
Hi @papofrito,

You should checkout first 1.x versions.
1.x -> Jelly Bean
2.x -> KitKat

https://github.com/bq/aquaris-5/tree/1.4.1-20140328-1139/mediatek/config/eastaeon89_wet_jb2 

Latest 1.x tag: 1.4.1-20140328-1139

```
git checkout 1.4.1-20140328-1139
./makeMtk -t eastaeon89_wet_jb2 n k
```

**Comment by papofrito** [comment]
Thank you very much, I will try asap!

**Comment by pmoncadaisla** [comment]
Great!

Let us know if everything went ok.

Rergads,

**Comment by papofrito** [comment]
Hi again. I'm trying to compile on a centos 6 64 bit vm, but I'm having problems with 64 bit libraries (./Cgen: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory) Can I get it compiled on a 64 bit install or I will need a 32 bit centos install?

**Comment by pmoncadaisla** [comment]
Hi @papofrito,

Can't help you with CentOS. Google recomends to use Ubuntu:

https://source.android.com/source/initializing.html

Regards,

**Comment by papofrito** [comment]
I'll try with an i386 install of CentOs, I will tell you the results. Thx.

**Comment by papofrito** [comment]
I installed some additional 32 bit libraries and it worked on centos 6 64 bit. I'm now interested on compiling kernel modules (*.ko) to avoid flashing my device, is out there any info/howto about this? Thx in advance
