### ISSUE TITLE
Can't compile kernel module (*.ko)

### ISSUE THREAD

**Issue by papofrito** [bq/aquaris-5#2]
Hi!

makeMtk help says:

./makeMtk e1k n k kernel/xxx/xxx
                : Build(full build) kernel component/module
                  under the path "kernel/xxx/xxx" for e1k project.

I'm trying to compile cifs module with this:

./makeMtk -t eastaeon89_wet_jb2 n k fs/cifs

but no cifs.ko is generated. There are no errors in console, process ends with:

Build kernel module PROJECT=eastaeon89_wet_jb2 PATH=fs/cifs
  Building modules, stage 2.
  MODPOST 0 modules
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux
WARNING: vmlinux: 'data_free_size_th' exported twice. Previous export was in vmlinux

What am I doing wrong?

Thx in advance

**Comment by papofrito** [comment]
It would be nice to have any response ...
Thx

**Comment by bqhook** [comment]
Hi,

Am Montag, 2. M�rz 2015, 01:14:39 schrieb papofrito:

> Hi!
> 
> makeMtk help says:
> 
> ./makeMtk e1k n k kernel/xxx/xxx
> 
> ```
>             : Build(full build) kernel component/module
> 
>               under the path "kernel/xxx/xxx" for e1k project.
> ```
> 
> I'm trying to compile cifs module with this:
> 
> ./makeMtk -t eastaeon89_wet_jb2 n k fs/cifs
> 
> but no cifs.ko is generated.

Enabling the module in question in the kernel config is still necessary,
for example with the diff below.

--------------- 8< ----------------
diff --git a/mediatek/config/eastaeon89_wet_jb2/autoconfig/kconfig/project b/mediatek/config/eastaeon89_wet_jb2/autoconfig/kconfig/project
index 8249d38..15a4531 100755
--- a/mediatek/config/eastaeon89_wet_jb2/autoconfig/kconfig/project
+++ b/mediatek/config/eastaeon89_wet_jb2/autoconfig/kconfig/project
@@ -8,3 +8,10 @@ CONFIG_POWER_EXT=n
 CONFIG_MTK_VIDEOCODEC_DRIVER=m
 CONFIG_USB_MTK_OTG=n
 CONFIG_USB_MTK_HDRC_HCD=n
+
+CONFIG_CIFS=m
+# CONFIG_CIFS_STATS is not set
+# CONFIG_CIFS_WEAK_PW_HASH is not set
+CONFIG_CIFS_XATTR=y
+CONFIG_CIFS_POSIX=y
+# CONFIG_CIFS_DEBUG2 is not set
--------------- 8< ----------------

Then your ./makeMtk -t eastaeon89_wet_jb2 n k fs/cifs should produce the
cifs.ko in ./kernel/out/fs/cifs/cifs.ko

Hope that helps
Heiko

**Comment by papofrito** [comment]
Great! I have managed to compile the kernel, and here we have cifs.ko :) My goal is to insmod this module in my running kernel. I have just tried to do it, but I have "Unknown symbol" errors. I think I need the config (.config) of my running kernel (official firmware), is there any way to obtain it? (android 4.2.1, kernel 3.4.5, compilation 1.4.2-20140509-1200)

Thx in advance

**Comment by bqhook** [comment]
Hi,

Am Freitag, 6. M�rz 2015, 05:15:43 schrieb papofrito:

> Great! I have managed to compile the kernel, and here we have cifs.ko :) My
> goal is to insmod this module in my running kernel. I have just tried to do
> it, but I have "Unknown symbol" errors.

Does it output any more helpful messages (like which symbols are missing)?
Does logcat provide anything helpful directly after the insmod fails?

> I think I need the config (.config)
> of my running kernel (official firmware), is there any way to obtain it?
> (android 4.2.1, kernel 3.4.5, compilation 1.4.2-20140509-1200)

at least in the config I build from the github sources IKCONFIG_PROC is active, 
so hopefully this is also true for the original kernel. In this case you 
should hopefully see a /proc/config.gz

Heiko

**Comment by papofrito** [comment]
Symbols not found are:

__stack_chk_guard
lockdep_init_map
mutex_lock_nested
kmem_cache_alloc_trace
__stack_chk_fail
debug_check_no_locks_freed
lock_acquire
lock_release
rcu_lock_map

Unfortunately, IKCONFIG_PROC is not active in my running kernel. Is there any alternative method for extracting kernel config?

Thx

**Comment by bqhook** [comment]
Hi,

I've tried to trace where these come from, and all seem to stem from different
debug or tracing mechanisms. The puzzling part is why these should be disabled
in the device kernel but be activated here.

The symbol mismatches itself come from these functions being compiled to
inline stub functions when the option in question is disabled.

Am Freitag, 6. M�rz 2015, 06:21:41 schrieb papofrito:

> Symbols not found are:
> 
> lockdep_init_map
> debug_check_no_locks_freed
> lock_acquire
> lock_release

from CONFIG_LOCKDEP

> mutex_lock_nested

from CONFIG_DEBUG_LOCK_ALLOC

> kmem_cache_alloc_trace

from CONFIG_TRACING

> __stack_chk_fail
> __stack_chk_guard

from CONFIG_CC_STACKPROTECTOR

> rcu_lock_map

from CONFIG_DEBUG_LOCK_ALLOC

Anyway, I've added another diff for the kernel config, which should disable
all mechanisms in question for this kernel too, so the symbol mismatch should
hopefully go away.

I just hope I didn't introduce any additional symbol mismatches now ;-)

Heiko

-------- 8< -------------
diff --git a/mediatek/config/eastaeon89_wet_jb2/autoconfig/kconfig/project b/mediatek/config/eastaeon89_wet_jb2/autoconfig/kconfig/project
index 8249d38..3e29ff8 100755
--- a/mediatek/config/eastaeon89_wet_jb2/autoconfig/kconfig/project
+++ b/mediatek/config/eastaeon89_wet_jb2/autoconfig/kconfig/project
@@ -8,3 +8,15 @@ CONFIG_POWER_EXT=n
 CONFIG_MTK_VIDEOCODEC_DRIVER=m
 CONFIG_USB_MTK_OTG=n
 CONFIG_USB_MTK_HDRC_HCD=n
+
+CONFIG_CIFS=m
+# CONFIG_CIFS_STATS is not set
+# CONFIG_CIFS_WEAK_PW_HASH is not set
+CONFIG_CIFS_XATTR=y
+CONFIG_CIFS_POSIX=y
+# CONFIG_CIFS_DEBUG2 is not set
+
+# CONFIG_DEBUG_LOCK_ALLOC is not set
+# CONFIG_TRACING is not set
+# CONFIG_LOCKDEP is not set
+# CONFIG_CC_STACKPROTECTOR is not set
diff --git a/mediatek/config/eastaeon89_wet_jb2/configs/EMMC_partition_size.mk b/mediatek/config/eastaeon89_wet_jb2/configs/EMMC_partition_size.mk
index 7750480..4d034d3 100755
--- a/mediatek/config/eastaeon89_wet_jb2/configs/EMMC_partition_size.mk
+++ b/mediatek/config/eastaeon89_wet_jb2/configs/EMMC_partition_size.mk
@@ -38,8 +38,8 @@ ifeq ($(MTK_EMMC_SUPPORT),yes)
 BOARD_PROTECT_FIMAGE_PARTITION_SIZE:=10M
 BOARD_PROTECT_SIMAGE_PARTITION_SIZE:=10M
 BOARD_SECROIMAGE_PARTITION_SIZE:=6M
-BOARD_SYSTEMIMAGE_PARTITION_SIZE:=650M
-BOARD_CACHEIMAGE_PARTITION_SIZE:=126M
-BOARD_USERDATAIMAGE_PARTITION_SIZE:=1023M
+BOARD_SYSTEMIMAGE_PARTITION_SIZE:=710M
+BOARD_CACHEIMAGE_PARTITION_SIZE:=516M
+BOARD_USERDATAIMAGE_PARTITION_SIZE:=2047M
 BOARD_FATIMAGE_PARTITION_SIZE:=0M
 endif 
diff --git a/mediatek/config/mt6589/autoconfig/kconfig/platform b/mediatek/config/mt6589/autoconfig/kconfig/platform
index ee50200..201a9b3 100755
--- a/mediatek/config/mt6589/autoconfig/kconfig/platform
+++ b/mediatek/config/mt6589/autoconfig/kconfig/platform
@@ -345,7 +345,7 @@ CONFIG_FORCE_MAX_ZONEORDER=11
 CONFIG_ALIGNMENT_TRAP=y
 # CONFIG_UACCESS_WITH_MEMCPY is not set
 # CONFIG_SECCOMP is not set
-CONFIG_CC_STACKPROTECTOR=y
+# CONFIG_CC_STACKPROTECTOR is not set
 # CONFIG_DEPRECATED_PARAM_STRUCT is not set
 # CONFIG_ARM_FLUSH_CONSOLE_ON_RESTART is not set

@@ -2147,14 +2147,14 @@ CONFIG_DEBUG_PREEMPT=y
 # CONFIG_RT_MUTEX_TESTER is not set
 CONFIG_DEBUG_SPINLOCK=y
 CONFIG_DEBUG_MUTEXES=y
-CONFIG_DEBUG_LOCK_ALLOC=y
-CONFIG_PROVE_LOCKING=y
+# CONFIG_DEBUG_LOCK_ALLOC is not set
+# CONFIG_PROVE_LOCKING is not set
 # CONFIG_PROVE_RCU is not set
 # CONFIG_SPARSE_RCU_POINTER is not set
-CONFIG_LOCKDEP=y
+# CONFIG_LOCKDEP is not set
 # CONFIG_LOCK_STAT is not set
 CONFIG_DEBUG_LOCKDEP=y
-CONFIG_TRACE_IRQFLAGS=y
+# CONFIG_TRACE_IRQFLAGS is not set
 # CONFIG_DEBUG_ATOMIC_SLEEP is not set
 # CONFIG_DEBUG_LOCKING_API_SELFTESTS is not set
 CONFIG_STACKTRACE=y
@@ -2186,7 +2186,7 @@ CONFIG_RCU_CPU_STALL_VERBOSE=y
 # CONFIG_DEBUG_PER_CPU_MAPS is not set
 # CONFIG_LKDTM is not set
 # CONFIG_CPU_NOTIFIER_ERROR_INJECT is not set
-CONFIG_FAULT_INJECTION=y
+# CONFIG_FAULT_INJECTION is not set
 # CONFIG_FAILSLAB is not set
 # CONFIG_FAIL_PAGE_ALLOC is not set
 # CONFIG_FAIL_MAKE_REQUEST is not set
@@ -2194,19 +2194,19 @@ CONFIG_FAULT_INJECTION=y
 # CONFIG_FAIL_MMC_REQUEST is not set
 # CONFIG_FAULT_INJECTION_DEBUG_FS is not set
 # CONFIG_DEBUG_PAGEALLOC is not set
-CONFIG_NOP_TRACER=y
-CONFIG_HAVE_FUNCTION_TRACER=y
-CONFIG_HAVE_FUNCTION_GRAPH_TRACER=y
-CONFIG_HAVE_DYNAMIC_FTRACE=y
-CONFIG_HAVE_FTRACE_MCOUNT_RECORD=y
-CONFIG_HAVE_C_RECORDMCOUNT=y
+# CONFIG_NOP_TRACER=y
+# CONFIG_HAVE_FUNCTION_TRACER is not set
+# CONFIG_HAVE_FUNCTION_GRAPH_TRACER is not set
+# CONFIG_HAVE_DYNAMIC_FTRACE is not set
+# CONFIG_HAVE_FTRACE_MCOUNT_RECORD is not set
+# CONFIG_HAVE_C_RECORDMCOUNT is not set
 CONFIG_RING_BUFFER=y
-CONFIG_EVENT_TRACING=y
-CONFIG_EVENT_POWER_TRACING_DEPRECATED=y
+# CONFIG_EVENT_TRACING is not set
+# CONFIG_EVENT_POWER_TRACING_DEPRECATED is not set
 CONFIG_RING_BUFFER_ALLOW_SWAP=y
-CONFIG_GENERIC_TRACER=y
-CONFIG_TRACING_SUPPORT=y
-CONFIG_FTRACE=y
+# CONFIG_GENERIC_TRACER is not set
+# CONFIG_TRACING_SUPPORT is not set
+# CONFIG_FTRACE is not set
 # CONFIG_FUNCTION_TRACER is not set
 # CONFIG_FTRACE_MODULE_SUPPORT is not set
 # CONFIG_FUNCTION_GRAPH_TRACER is not set
@@ -2403,9 +2403,9 @@ CONFIG_MEDIATEK_SOLUTION=y
 # CONFIG_ARCH_MT6577 is not set
 # CONFIG_ARCH_MT8320 is not set
 CONFIG_ARCH_MT6589=y
-CONFIG_MTK_SCHED_TRACERS=y
+# CONFIG_MTK_SCHED_TRACERS is not set
 # CONFIG_MTK_KERNEL_MARKER is not set
-CONFIG_MT65XX_TRACER=y
+# CONFIG_MT65XX_TRACER is not set
 CONFIG_MTPROF_CPUTIME=y
 CONFIG_MTPROF_IRQ_DURATION=y
 # CONFIG_MTK_AEE_FEATURE is not set

**Comment by papofrito** [comment]
Thx a lot :) I'll try asap. If works, It can't be a goog point to add this patch to the source tree. I'll tell you the results, thank you again.

**Comment by papofrito** [comment]
Well, that patch did the trick, I have finally my cifs.ko :))) Thank you very much
